### ISSUE TITLE
Rebranding to Kentico Kontent

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/kontent-delivery-sdk-java#86]
Hi @aweigold !
We've just renamed Kentico Cloud to [Kentico Kontent](https://kontent.ai/blog/moving-to-caas-with-kentico-kontent). We are in the process of renaming all SDKs, developer tools, and sample apps. Please consider renaming your project (code: namespaces, classes; repo, wiki, GH topics, etc.) to Kentico Kontent. See the guidelines at https://gitter.im/Kentico/Kontent?at=5d8b643d692d464f7969c6d9.

Thank you!

**Comment by aweigold** [comment]
This should largely be done.  Remaining issue is to reach out to sonatype to allow publishing to `kentico.kontent` instead of `com.kenticocloud` in the Maven central snapshot and release repositories.

This can usually be done via their Jira system, but would probably be streamlined if someone working from Kentico can perform it.

They may not allow `kentico.kontent`, in which case, I would recommend publishing to `ai.kontent` as they can verify that domain ownership.

Note, publishing to `ai.kontent` will not reflect on package names.  They can remain `kentico.kontent` per the guidelines posted in gitter.

Assigning this to @petrsvihlik to triage on his end.  Once this is complete, you can assign back to me and I'll complete the 3.0.0 release process.

**Comment by aweigold** [comment]
FYI, I did confirm before renaming that the CI was functioning and publishing successfully to Maven Central's snapshot repository: https://oss.sonatype.org/content/repositories/snapshots/com/kenticocloud/delivery/3.0.0-SNAPSHOT/

**Comment by petrsvihlik** [comment]
I created a request at https://issues.sonatype.org/browse/OSSRH-52022 and I'm reassigning this task to @Simply007 as I'll be off for the whole of October.
Please coordinate the rebranding and the release of the new version with him.
Thank you!

**Comment by petrsvihlik** [comment]
https://issues.sonatype.org/browse/OSSRH-52104

**Comment by Simply007** [comment]
Hello @aweigold,

petrs (@petrsvihlik) should be already granted by `com.github.kentico` (https://issues.sonatype.org/browse/OSSRH-52104).

If you have anything to discuss, feel free to content me here on you use Gitter: https://gitter.om/Simply007

Is there anything I could help you with right now?

**Comment by aweigold** [comment]
I'll work on a release tonight, and update here.

**Comment by aweigold** [comment]
Update:

I tried publishing to the new group name via travis (https://travis-ci.org/Kentico/kontent-delivery-sdk-java/builds/595577983), and my user (`aweigold`) did not have deploy privileges.  I commented on the sonatype ticket (https://issues.sonatype.org/browse/OSSRH-52104).

**Comment by Simply007** [comment]
Thank for info 
OK, I have subscribed to the ticket updates. If they want to authenticate you again by creating some repo, I could do it for you.

**Comment by Simply007** [comment]
Now you should be able to publish the package.

**Comment by aweigold** [comment]
I attempted to publish yesterday morning, but due to issues with oss.sonatype.org being overloaded and timing out, I had to delay it.  I'll make another attempt tonight.

**Comment by Simply007** [comment]
All right - wish you good luck!

**Comment by aweigold** [comment]
Released on central.  I'll look in a few hours to validate it's propagating, and close.

**Comment by aweigold** [comment]
Looks like it's released:
https://repo.maven.apache.org/maven2/com/github/kentico/delivery/3.0.0/

**Comment by Simply007** [comment]
Great @aweigold! 

I have just one question about `artifactId`. You have set it as `delivery`. Wouldn't be better to set it to `kontent-delivery` to have the package identification like that: `com.github.kentico:kontent-delivery:3.0.0`? 
I don't know if `artifactId` should be bound to the package namespace (`kentico.kontent.delivery`), but it feels better from my point of view to have them somehow similar.

We have used `kontent` in package names to distinguish kontent and ems packages and to prevent confusion (i.e. [JS SDK](https://www.npmjs.com/package/@kentico/kontent-delivery) [PHP SDK](https://packagist.org/packages/kentico/kontent-delivery-sdk-php)) with EMS packages.

I don't know what are the options since the package is already released - what do you think about that?

**Comment by aweigold** [comment]
As far as renaming `delivery` to `kontent-delivery`, that is no problem.  I can make a commit and do a new release.

As far as the package `groupId`, that is bound to what we have rights to deploy to on Maven Central.  Sonatype requires this to be a domain controlled by the organization.  Hence why it's `com.github.kentico`.  If desired, this could be `ai.kontent` if the domain is validated, but that's it.

As far as the package namespace matching the groupId... I tend to agree, but was following the guidance from the gitter thread.  I'll leave it to you @Simply007 on which way to go on that one.

After I hear back on the package namespace to groupId inconsistency, I will push another release to rename to `kontent-delivery`.

**Comment by Simply007** [comment]
OK let's leave the namespaces as they are and set the `groupId` to `kontent-delivery`.

Thank you so much @aweigold!

**Comment by aweigold** [comment]
@MikeSvacha the package to import is `kentico.kontent.delivery`.

See here: https://github.com/Kentico/kontent-delivery-sdk-java/blob/master/kontent-delivery/src/main/java/kentico/kontent/delivery/DeliveryClient.java

**Comment by Simply007** [comment]
According to the [API changelog](https://docs.kontent.ai/reference/api-changelog) there should be new endpoints set in the SDK.

There are still old domains for [delivery ](https://github.com/Kentico/kontent-delivery-sdk-java/blob/master/kontent-delivery/src/main/java/kentico/kontent/delivery/DeliveryOptions.java#L63) as well as [preview ](https://github.com/Kentico/kontent-delivery-sdk-java/blob/master/kontent-delivery/src/main/java/kentico/kontent/delivery/DeliveryOptions.java#L78) that will stop working by the end of March 2020.

There are also other remaining occurrences of the old names - mainly API reference URLs:
https://github.com/Kentico/kontent-delivery-sdk-java/search?q=kenticocloud&unscoped_q=kenticocloud

**Comment by petrsvihlik** [comment]
There are still some occurrences of "Kentico Cloud" in the code: https://github.com/Kentico/kontent-delivery-sdk-java/search?q=cloud&unscoped_q=cloud

**Comment by Simply007** [comment]
Should all be fixed.
